// <auto-generated />
namespace Gymbokning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gymbokningv05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gymbokningv05));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141351096_Gymbokning v0.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
